version: "3.8"
services:
  web:
    build: .
    container_name: flask
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=DigitalHospital

    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js


volumes:
  mongo-data:


